apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs123
spec:
  replicas: 5
  selector:
    matchLabels:
      type: httpd
  template:
    metadata:
      name: pod1
      labels:
        type: httpd
    spec:
      containers:
        - name: mycontainer
          image: rutvijapatil/mywebsite
          ports:
            - name: http
              containerPort: 80
