version: '3.8'

services:
  busybox:
    image: busybox

  httpd:
    image: httpd
    ports:
      - "9090:80"

  nginx:
    image: nginx
    ports:
      - "8082:80"

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

